# Generated by Django 4.2.6 on 2025-03-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_being_followed',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_following',
            new_name='user_id',
        ),
    ]
